### ISSUE TITLE
Age-based coverage of PMC

### ISSUE THREAD

**Issue by ginacuomo** [mrc-ide/malariasimulation#303]
At present, the coverage of PMC is based on calendar time rather than the age of the individual. The PMC modellers in our team have stated it would be useful to be able to model PMC coverage based on the age at the time of the dose (similar to how you can alter vaccination coverage).

**Comment by pwinskill** [comment]
Is this realted to https://github.com/mrc-ide/malariasimulation/pull/291 @ginacuomo ?

**Comment by ginacuomo** [comment]
Ahhh potentially @pwinskill - when I spoke to Paul yesterday he said to open an issue but maybe this is resolved?? This was based on conversations with Ishana and Andria who said they were running the model without PMC and then implementing it in post-processing to get around this issue of not being able to have difference coverage depending on the age of the children. Let me know if I should close this issue @plietar

**Comment by plietar** [comment]
It's only tangentially related in that it is about the same function. #291 was just clarifying some documentation of the existing behaviour. The feature @ginacuomo is after is still not there.

I think we should change the `coverages` parameter from a vector of size `length(timesteps)` to a matrix of size `length(timesteps) x length(ages)`.

**Comment by pwinskill** [comment]
@ginacuomo I'd be interested to know a little more about the motivating case for this change. WHO reccommends that PMC is the administration of a full treatment course of an antimalarial medicine at predefined intervals, and as such it isn't clear to me how/why we would implement coverage varying by age (beyond coverage varying by time which would impact the coverage of the cohort).
